version: 2
jobs:
  build:
    working_directory: ~/udacity-devops-microservices
    docker:
      - image: python:3.7.3-stretch  # primary container for the build job

    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          command: |
            pip install pipenv
            pipenv install
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          command: |
            . venv/bin/activate
            # make lint