version: 2
jobs:
  build:
    working_directory: ~/udacity-devops-microservices
    docker:
      - image: python:3.7.3-stretch  # primary container for the build job

    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-